### ISSUE TITLE
After transform, path is filled incorrectly due to spurious M commands

### ISSUE THREAD

**Issue by sw46** [mathandy/svgpathtools#124] opened 2020-11-07 00:09 UTC
Sample code:

```
from svgpathtools import svg2paths, wsvg

paths, attributes = svg2paths("in.svg")
paths = [p.scaled(sx=1,sy=-1) for p in paths]
wsvg(paths, attributes=attributes, filename="out.svg")
```

in.svg:

```
<?xml version="1.0" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xlink="http://www.w3.org/1999/xlink" baseProfile="full" height="600px" version="1.1" viewBox="-153.0479963719098 -36.49641752855996 306.0959927438195 436.1412681771202" width="422px">
        <defs/>
        <path d="M -0.6113251071690655,363.14843312000005 C -0.6113251071690655,363.14843312000005 -0.23645510716906415,297.0918730000001 -55.15820310716906,233.84960000000007 C -79.46132110716906,205.86462000000006 -127.88984136716905,174.25018000000006 -127.38476510716907,107.58007000000006 C -127.10925050716907,71.21214000000003 -126.37531310716906,1.5152100000000672 -0.6113251071690655,5.684341886080802e-14 C 125.15266489283093,1.5152100000000814 127.10925489283093,71.21214000000003 127.38476489283094,107.58007000000006 C 127.88984489283094,174.25018000000006 79.46327489283092,205.86462000000006 55.160154892830874,233.84960000000007 C 0.23840489283093547,297.0918730000001 -0.6113251071690726,363.14843312000005 -0.6113251071690797,363.14843312000005" fill="green" fill-opacity="1" stroke="black" stroke-width="2"/>
</svg>
```

The program generates out.svg:

```
<?xml version="1.0" ?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xlink="http://www.w3.org/1999/xlink" baseProfile="full" height="600px" version="1.1" viewBox="-153.0479963719098 -399.64485064856024 306.0959927438195 436.1412681771202" width="422px">
        <defs/>
        <path d="M -0.6113251071690655,-363.14843312000005 C -0.6113251071690655,-363.14843312000005 -0.23645510716906415,-297.0918730000001 -55.15820310716906,-233.84960000000007 C -79.46132110716906,-205.86462000000006 -127.88984136716905,-174.25018000000006 -127.38476510716909,-107.58007000000006 M -127.38476510716907,-107.58007000000006 C -127.10925050716907,-71.21214000000003 -126.37531310716906,-1.5152100000000672 -0.6113251071690655,-7.105427357601002e-14 M -0.6113251071690655,-5.684341886080802e-14 C 125.15266489283093,-1.5152100000000814 127.10925489283093,-71.21214000000003 127.38476489283094,-107.58007000000006 C 127.88984489283094,-174.25018000000006 79.46327489283091,-205.86462000000006 55.16015489283082,-233.84960000000007 M 55.160154892830874,-233.84960000000007 C 0.23840489283093547,-297.0918730000001 -0.6113251071690655,-363.14843312000005 -0.6113251071690655,-363.14843312000005" fill="green" fill-opacity="1" stroke="black" stroke-width="2"/>
</svg>
```

Notice the additional M points that appear in out.

This messes up the fill in both chrome and imagemagick:

![in](https://user-images.githubusercontent.com/70744252/98425403-3537d700-2095-11eb-8574-4f16b04e6902.png)
![out](https://user-images.githubusercontent.com/70744252/98425408-379a3100-2095-11eb-839e-9bf2605cf65a.png)

The following change seems to fix it:

```
diff --git a/svgpathtools/path.py b/svgpathtools/path.py
index 97a0036..00acb36 100644
--- a/svgpathtools/path.py
+++ b/svgpathtools/path.py
@@ -2498,7 +2498,8 @@ class Path(MutableSequence):
             # If the start of this segment does not coincide with the end of
             # the last segment or if this segment is actually the close point
             # of a closed path, then we should start a new subpath here.
-            if current_pos != seg_start or \
+            if current_pos is None or \
+                    not np.isclose(current_pos, seg_start) or \
                     (self_closed and seg_start == end and use_closed_attrib):
                 if rel:
                     _seg_start = seg_start - current_pos if current_pos is not None else seg_start
```

**Comment by tatarize** [comment] 2020-12-02 05:19
Confirmed. This really does do this and for the reasons you gave. The real issue here is that the closing a path should actually include a Close object rather than using coincident points to indicate that. However when these points are scaled and moved they don't always end up as coincident at they were before. Simulating the original path and the new path very much does correct this. If we are not None and we are very close to that point the strong indication is that we have a closed path.

The real corrections would be to implement the changes in svg.path 4.0+

But, this suffices to correct transformed coincident points not acting as a closed path semaphore.

**Comment by mathandy** [comment] 2020-12-09 06:38
This is a bug in the `path.scale()` function.  If a continuous path goes in, a continuous path should come out.  The behavior shown in your example is caused by segments being transformed individually and floating point error resulting in the endpoints/joints not aligning perfectly anymore.

This also is likely to happen for `rotate`, `translate`,  `scale`, and `transform`.

I've got a fix ready -- running tests now, I'll push it if it passes.

**Comment by mathandy** [comment] 2020-12-09 06:51
I believe this is now fixed.

**Closed by mathandy** 2020-12-09 06:51 UTC

**Comment by mathandy** [comment] 2020-12-09 06:55
Oh, and thanks @sw46 !

**Comment by mathandy** [comment] 2020-12-09 06:55
and thanks @tatarize !
